### ISSUE TITLE
Can export texture from a sprite (from atlas)

### ISSUE THREAD

**Issue by natsupy** [miguel12345/UnityTextureExporter#1]
Like a title, in this can use like that?

**Comment by miguel12345** [comment]
Hi,

That's a good idea! We don't support it atm, but I'll implement it as soon as possible.

Thank you!

**Comment by miguel12345** [comment]
The issue has been fixed. Check out the latest commit!

**Comment by natsupy** [comment]
Thank you, it works perfectly!
